/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Model.Parameters;

/**
 *
 * @author Kenneth
 */
public class NewVMS extends javax.swing.JDialog {
    Parameters newVMSParam;
    /**
     * Creates new form NewVMS
     * @param parent
     * @param modal
     */
    public NewVMS(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        newVMSParam = new Parameters();
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Parameters showDialog(){
        setVisible(true);
        return newVMSParam;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_Cancel = new javax.swing.JToggleButton();
        btn_Create = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CBFetchPolicy = new javax.swing.JComboBox<>();
        CBPlacementPolicy = new javax.swing.JComboBox<>();
        CBReplacementPolicy = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        SPRSMMin = new javax.swing.JSpinner();
        SPRSMMax = new javax.swing.JSpinner();
        CBReplacementScope = new javax.swing.JComboBox<>();
        CMCleaningPolicy = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        SPLoadControl = new javax.swing.JSpinner();
        SPPhysicalMemory = new javax.swing.JSpinner();
        SPVirtualMemory = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        SPPageSize = new javax.swing.JSpinner();

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("KB");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("New Virtual Memory System");

        btn_Cancel.setText("Cancel");
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });

        btn_Create.setText("Create");
        btn_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CreateActionPerformed(evt);
            }
        });

        jLabel5.setText("Fetch Policy");

        jLabel7.setText("Placement Policy");

        jLabel8.setText("Replacement Policy");

        jLabel9.setText("Resident Set Management");

        jLabel10.setText("Replacement Scope ");

        jLabel11.setText("Cleaning Policy");

        jLabel12.setText("Load Control");

        CBFetchPolicy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Demand", "Prepaging" }));
        CBFetchPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBFetchPolicyActionPerformed(evt);
            }
        });

        CBPlacementPolicy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First available", "Next available" }));
        CBPlacementPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPlacementPolicyActionPerformed(evt);
            }
        });

        CBReplacementPolicy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIFO", "LRU", "LFU", "MRU", "Second-chance" }));
        CBReplacementPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBReplacementPolicyActionPerformed(evt);
            }
        });

        jLabel13.setText("Minimum");

        jLabel14.setText("Maximum");

        CBReplacementScope.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Global", "Local" }));
        CBReplacementScope.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBReplacementScopeActionPerformed(evt);
            }
        });

        CMCleaningPolicy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Demand", "Pre-cleaning" }));
        CMCleaningPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMCleaningPolicyActionPerformed(evt);
            }
        });

        jLabel15.setText("Physical Memory (KB)");

        jLabel16.setText("Virtual Memory (KB)");

        SPLoadControl.setModel(new javax.swing.SpinnerNumberModel(5, 0, null, 1));

        SPPhysicalMemory.setModel(new javax.swing.SpinnerNumberModel(1024, 1024, null, 1024));

        SPVirtualMemory.setModel(new javax.swing.SpinnerNumberModel(1024, 1024, null, 1024));

        jLabel2.setText("Page Size (KB)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)))
                            .addComponent(jLabel16)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Create)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Cancel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel15))
                                        .addGap(117, 117, 117))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(183, 183, 183)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(SPPageSize)
                                    .addComponent(CBPlacementPolicy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CBFetchPolicy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CBReplacementScope, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CBReplacementPolicy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SPRSMMin)
                                    .addComponent(SPRSMMax)
                                    .addComponent(CMCleaningPolicy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SPLoadControl, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SPPhysicalMemory, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SPVirtualMemory))))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CBFetchPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CBPlacementPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CBReplacementPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(SPRSMMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(SPRSMMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CBReplacementScope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(CMCleaningPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(SPLoadControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(SPPhysicalMemory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(SPVirtualMemory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SPPageSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cancel)
                    .addComponent(btn_Create))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CreateActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_CreateActionPerformed

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        newVMSParam = null;
        this.dispose();
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void CBFetchPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBFetchPolicyActionPerformed
        switch(CBFetchPolicy.getSelectedIndex()){
            case 0:
                newVMSParam.setFethPolicy(Parameters.FethPolicy.DEMAND);
                break;
            case 1:
                newVMSParam.setFethPolicy(Parameters.FethPolicy.PREPAGING);
                break;
        }
    }//GEN-LAST:event_CBFetchPolicyActionPerformed

    private void CBPlacementPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPlacementPolicyActionPerformed
        switch(CBPlacementPolicy.getSelectedIndex()){
            case 0:
                newVMSParam.setPlacementPolicy(Parameters.PlacementPolicy.FIRST);
                break;
            case 1:
                newVMSParam.setPlacementPolicy(Parameters.PlacementPolicy.FIRST);
                break;
        }
    }//GEN-LAST:event_CBPlacementPolicyActionPerformed

    private void CBReplacementPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBReplacementPolicyActionPerformed
        switch(CBReplacementPolicy.getSelectedIndex()){
            case 0:
                newVMSParam.setReplacementPolicy(Parameters.ReplacementPolicy.FIFO);
                break;
            case 1:
                newVMSParam.setReplacementPolicy(Parameters.ReplacementPolicy.LFU);
                break;
            case 2:
                newVMSParam.setReplacementPolicy(Parameters.ReplacementPolicy.LRU);
                break;
            case 3:
                newVMSParam.setReplacementPolicy(Parameters.ReplacementPolicy.MRU);
                break;
            case 4:
                newVMSParam.setReplacementPolicy(Parameters.ReplacementPolicy.SECONDCHANCE);
                break;
        }
    }//GEN-LAST:event_CBReplacementPolicyActionPerformed

    private void CBReplacementScopeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBReplacementScopeActionPerformed
        switch(CBReplacementScope.getSelectedIndex()){
            case 0:
                newVMSParam.setReplacementScope(Parameters.ReplacementScope.GLOBAL);
                break;
            case 1:
                newVMSParam.setReplacementScope(Parameters.ReplacementScope.LOCAL);
                break;
        }
    }//GEN-LAST:event_CBReplacementScopeActionPerformed

    private void CMCleaningPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMCleaningPolicyActionPerformed
        switch(CMCleaningPolicy.getSelectedIndex()){
            case 0:
                newVMSParam.setCleaningPolicy(Parameters.CleaningPolicy.DEMAND);
                break;
            case 1:
                newVMSParam.setCleaningPolicy(Parameters.CleaningPolicy.PRECLEANING);
                break;
        }
    }//GEN-LAST:event_CMCleaningPolicyActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBFetchPolicy;
    private javax.swing.JComboBox<String> CBPlacementPolicy;
    private javax.swing.JComboBox<String> CBReplacementPolicy;
    private javax.swing.JComboBox<String> CBReplacementScope;
    private javax.swing.JComboBox<String> CMCleaningPolicy;
    private javax.swing.JSpinner SPLoadControl;
    private javax.swing.JSpinner SPPageSize;
    private javax.swing.JSpinner SPPhysicalMemory;
    private javax.swing.JSpinner SPRSMMax;
    private javax.swing.JSpinner SPRSMMin;
    private javax.swing.JSpinner SPVirtualMemory;
    private javax.swing.JToggleButton btn_Cancel;
    private javax.swing.JToggleButton btn_Create;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner3;
    // End of variables declaration//GEN-END:variables
}
